# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: ${MONGODB_CONTAINER_NAME:-mongo-db}
    restart: always
    env_file:
      .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMINUSERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMINPASSWORD:-1234}
    ports:
      -  ${MONGODB_PORT:-27017}:27017

  mongo-express:
    image: mongo-express:latest
    container_name: ${MONGOEXPRESS_CONTAINER_NAME:-mongo-ui}
    restart: always
    env_file:
      .env
    ports:
      - ${MONGOEXPRESS_PORT:-8081}:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD:-1234}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_CONTAINER_NAME:-mongo-db}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD:-admin}