# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      -  27017:27017

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-ui
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ''
      ME_CONFIG_MONGODB_ADMINPASSWORD: ''
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin